const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('vm'),fs=require('fs');
function setup(){const elements=new Map(),timers=[];function el(){const classes=new Set(['hidden']);return {textContent:'',classes,classList:{add:x=>classes.add(x),remove:x=>classes.delete(x),toggle:(x,b)=>b?classes.add(x):classes.delete(x)}};}
 const document={getElementById:id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id);},createElement:()=>({remove(){this.removed=true;}})};
 const window={currentRoomId:'r'};vm.runInNewContext(fs.readFileSync('client/js/media-ui.js','utf8'),{window,document,setTimeout:fn=>{timers.push(fn);return timers.length;},clearTimeout:()=>{}});return {ui:window.MediaUI,window,elements,timers};}
test('receives remote bilingual subtitles without any speech recognition API',()=>{const t=setup();t.ui.receive({roomId:'r',from:'电脑',originalText:'Hello',translatedText:'你好'});assert.equal(t.elements.get('receivedOriginal').textContent,'Hello');assert.equal(t.elements.get('receivedTranslated').textContent,'你好');assert.equal(t.elements.get('receivedCaption').classes.has('hidden'),false);t.ui.clearCaption();assert.equal(t.elements.get('receivedCaption').classes.has('hidden'),true);});
test('late subtitles from another room or after leaving are ignored',()=>{const t=setup();t.ui.receive({roomId:'other',originalText:'No'});assert.equal(t.elements.size,0);t.window.currentRoomId=null;t.ui.receive({roomId:'r',originalText:'No'});assert.equal(t.elements.size,0);});
test('blocked audible autoplay falls back to muted video and offers user playback',async()=>{const t=setup(),children=[];const tile={querySelector:()=>null,appendChild:b=>children.push(b)};const video={muted:false,plays:0,async play(){this.plays++;if(this.plays===1)throw Error('NotAllowed');}};await t.ui.play(video,tile);assert.equal(video.muted,true);assert.equal(children.length,1);await children[0].onclick();assert.equal(video.muted,false);assert.equal(children[0].removed,true);});

test('listener translation updates only current caption and cannot leak after leave',()=>{const t=setup();t.ui.receive({id:1,roomId:'r',originalText:'Bonjour',translatedText:'Hello'});t.ui.updateTranslation({id:1,roomId:'r',translatedText:'你好'});assert.equal(t.elements.get('receivedTranslated').textContent,'你好');t.ui.receive({id:2,roomId:'r',originalText:'Merci',translatedText:'Thanks'});t.ui.updateTranslation({id:1,roomId:'r',translatedText:'迟到'});assert.equal(t.elements.get('receivedTranslated').textContent,'Thanks');t.ui.clearCaption();t.ui.updateTranslation({id:2,roomId:'r',translatedText:'退出后'});assert.equal(t.elements.get('receivedCaption').classes.has('hidden'),true);});
